package it.ats.esempioimpiegatojdbc.modello.dao.test;

import java.util.Date;

//import org.junit.Before;
//import org.junit.Rule;
//import org.junit.Test;
//import org.junit.rules.ExpectedException;

import it.ats.esempioimpiegatojdbc.modello.Impiegato;
import it.ats.esempioimpiegatojdbc.modello.dao.DAOImpiegato;
import it.ats.esempioimpiegatojdbc.modello.dao.DataSource;
import it.ats.esempioimpiegatojdbc.modello.dao.eccezioni.DAOException;

public class TestDAOImpiegato {
/*
	private DataSource dataSource;
	private DAOImpiegato daoImpiegato;

	@Rule
	public ExpectedException thrown = ExpectedException.none();

	@Before
	public void setUp() throws Exception {
		dataSource = DataSource.getInstance();
		daoImpiegato = DAOImpiegato.getInstance();
	}

	// Provo ad inserire un impiegato con una matricola già esistente e
	// verifico che rilanci eccezione.
	// Il Test va a buon fine se DAOException viene sollevata.
	@Test(expected = DAOException.class)
	public void testInserisci() throws DAOException {
		Impiegato impiegato = new Impiegato(31888, "Nicola", "Verdi", 'M', new Date(78, 11, 1), 1600, "Via Napoli 123");
		daoImpiegato.inserisci(dataSource.getConnection(), impiegato);
	}
*/
}
